services:
  cdrsandbox:
    depends_on:
      clickhouse:
        condition: service_healthy
    image: cdrsandbox
    build:
      context: .
      dockerfile: CDRSandbox/Dockerfile
    ports:
      - "${CDRSANDBOX_HTTP_PORT}:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  
  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    ports:
      - "${CLICKHOUSE_PORT}:8123" # ODBC and JDBC and HTTP
      - "${CLICKHOUSE_NATIVE_PORT}:9000" # native clickhouse protocol
      - "${CLICKHOUSE_MYSQL_PORT}:9004" # MySQL interface
      - "${CLICKHOUSE_POSTGRES_PORT}:9005" # PostgreSQL interface
    environment: # taken from https://hub.docker.com/r/clickhouse/clickhouse-server/
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ulimits:
      nofile: 262144 # increase file descriptors
    volumes:
      - ./DockerConfigs/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
